[#module-dependencies]
== Module dependencies

There are several ways to influence the beans that are being bootstrapped with a module, by passing information from the configuration to the actual module ApplicationContext.

[#across-depends]
=== @AcrossDepends

==== Using @AcrossDepends on a module descriptor
Using AcrossDepends annotation on a module descriptor class you can avoid beans or Configurations from being created based on the presence of other modules.

* required modules: the component will only be created if all the _required_ modules are present
* optional modules: the component will only be created if at least one of the _optional_ modules is present


[#conditional-on-across-module]
=== @ConditionalOnAcrossModule

[discrete]
==== Using @ConditionalOnAcrossModule on a module

Using AcrossDepends annotation on a component class you can avoid beans or Configurations from being created based on the presence of other modules.

* allOf modules: the component will only be created if all the _allOf_ modules are present
* anyOf modules: the component will only be created if at least one of the _anyOf_ modules is present
* noneOf modules: the component will only be created if none of the _noneOf_ modules are present

[discrete]
==== Using @ConditionalOnAcrossModule on component classes
expression will be evaluated against the module context - as usual - beans from earlier modules will be available

[#conditionals]
=== Conditionals
Any Spring conditional can be used to determine if a bean should be created.