[[test-annotations]]
[#annotations]
== Annotations

The Across Test library also provides a set of Across-specific annotations that extend the default Spring Testing annotations (eg `@ContextConfiguration`) to support `AcrossContext` setups.

[[annotation-across-test-configuration]]
[#across-test-configuration]
=== @AcrossTestConfiguration
Class-level annotation to be used as an alternative to `<<developing-applications.adoc#enable-across-context,@EnableAcrossContext>>`.
Like `@EnableAcrossContext` this annotation will configure and bootstrap an `AcrossContext` but also add support for:

* <<test-datasources,test datasources>>
* easily exposing additional types for the scope of the test
* resetting the database before bootstrap
* creating a `MockMvc` bean instantiated with all dynamically registered filters from the context, when used in a `<<across-web-app-configuration,@AcrossWebAppConfiguration>>` test class

When using either `@EnableAcrossContext` or `@AcrossTestConfiguration`, all beans exposed can be wired directly in the unit test class.

.Example using @AcrossTestConfiguration
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@RunWith(SpringJUnit4ClassRunner.class)
@DirtiesContext
@ContextConfiguration
public class TestSample
{
	@Autowired
	private MyExposedBean myExposedBean;

	@Test
	public void doSomethingWithMyExposedBean() {
		...
	}

	@AcrossTestConfiguration(modules = MyModule.NAME, expose = MyExposedBean.class)
	protected static class Config
	{
	}
}
----

[[acrosswebappconfiguration]]
[#across-web-app-configuration]
=== @AcrossWebAppConfiguration
Class-level annotation that sets up a `@WebAppConfiguration` test that uses a `<<mock-across-servlet-context,MockAcrossServletContext>>` for initialization.
`@AcrossWebAppConfiguration` contains a `@ContextConfiguration` annotation, unless additional annotations are specified, it will load static innter `@Configuration` classes of the annotated test class.

When using this annotation on a test class the `MockAcrossServletContext` instance can be autowired for introspection.
In combination with an inner static `@AcrossTestConfiguration` class, this will support a `MockMvc` instance initialized with all dynamically registered filters.

.Example combining @AcrossWebAppConfiguration and @AcrossTestConfiguration
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@RunWith(SpringJUnit4ClassRunner.class)
@DirtiesContext
@AcrossWebAppConfiguration
@TestPropertySource( properties = "acrossWebModule.resources.versioning.enabled=false" )
public class TestSample
{
    @Autowired
    private MockAcrossServletContext servletContext;

	@Autowired
	private MockMvc mvc;

	@Test
	public void resourceUrlEncodingFilterShouldNotBeRegistered() {
        assertNull( servletContext.getFilterRegistration( ResourceUrlEncodingFilterConfiguration.FILTER_NAME ) );
	}

	@Test
	public void staticResourceShouldBeReturned() {
	    mvc.perform( get( "/across/resources/static/testResources/test.txt" ) )
           .andExpect( status().isOk() )
	}

	@AcrossTestConfiguration(modules = { AcrossWebModule.NAME })
	protected static class Config
	{
	}
}
----

[[expose-for-test]]
=== @ExposeForTest
Class-level annotation that can be used to manually expose components for tests.
It can be added to the level of the Across context configuration (`@EnableAcrossContext` or `@AcrossTestConfiguration`), as well as unit test class level when working with `@SpringBootTest`.

.Example using @ExposeForTest for a manual Across context
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@RunWith(SpringJUnit4ClassRunner.class)
@DirtiesContext
@AcrossWebAppConfiguration
@TestPropertySource( properties = "acrossWebModule.resources.versioning.enabled=false" )
public class TestSample
{
	// Note that @AcrossTestConfiguration has an expose() attribute
	// that also allows exposing additional components
	@ExposeForTest(MyComponent.class)
	@AcrossTestConfiguration(modules = { AcrossWebModule.NAME }, expose = MyOtherComponent.class)
	protected static class Config
	{
	}
}
----

.Example using @ExposeForTest for an Across application test
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@RunWith(SpringJUnit4ClassRunner.class)
@WebIntegrationTest(randomPort = true)
@SpringBootTest(classes = MyApplication.class)
@ExposeForTest(MyComponent.class)
public class TestSpringBootWebIntegration
{
}
----
