= Across Application Descriptor

On this page, you will:

* [*] Learn about the central entry point of an Across application.
* [*] Learn more about the bootstrapping of an Across application.

[[across-application]]
[#across-application]
== @AcrossApplication

The Across application descriptor is the central entry point of our application and is described by the `@AcrossApplication` annotation.
`@AcrossApplication` can be used as an alternative for `@SpringBootApplication` when defining an application.
In addition to default context configuration options, it also adds selected xref:ROOT:spring-boot-compatibility.adoc#spring-boot[Spring Boot autoconfiguration classes] and enables xref:default-modules.adoc#dynamic-across-modules[dynamic modules].



.Minimal example of a Spring Boot based Across application
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@AcrossApplication( modules = {} ) # <1>
public class DemoApplication
{
	public static void main( String[] args ) {
		SpringApplication.run( DemoApplication.class, args ); # <2>
	}
}
----

<1> `@AcrossApplication` annotation that defines which beans are present.
<2> Launch a Spring application when the `main` method is executed.

During application startup, logging provides some default context about what is happening.
In the following snippet, we can see which modules are being bootstrapped when our application is started.


.Abbreviated logging output during application startup
----
...
INFO --- [ost-startStop-1] c.f.a.c.AcrossDynamicModulesConfigurer   : Adding package based APPLICATION module DemoApplicationModule, resources: demo, base package: com.example.demo.application # <1>
INFO --- [ost-startStop-1] c.f.a.c.c.bootstrap.AcrossBootstrapper   : ---
INFO --- [ost-startStop-1] c.f.a.c.c.bootstrap.AcrossBootstrapper   : AcrossContext: DemoApplication (AcrossContext-1)
INFO --- [ost-startStop-1] c.f.a.c.c.bootstrap.AcrossBootstrapper   : Bootstrapping 2 modules in the following order: # <2>
INFO --- [ost-startStop-1] c.f.a.c.c.bootstrap.AcrossBootstrapper   : 1 - DemoApplicationModule [resources: demo]: class com.foreach.across.core.DynamicAcrossModule$DynamicApplicationModule
INFO --- [ost-startStop-1] c.f.a.c.c.bootstrap.AcrossBootstrapper   : 2 - AcrossContextPostProcessorModule [resources: AcrossContextPostProcessorModule]: class com.foreach.across.core.AcrossContextConfigurationModule
INFO --- [ost-startStop-1] c.f.a.c.c.bootstrap.AcrossBootstrapper   : ---
...
----

<1> Creates a dynamic application module for the application being bootstrapped, based on the *application* package.
<2> Show which modules are bootstrapped as well as the order they are bootstrapped in.

[[embedded-servlet-container]]
=== Embedded servlet container
Using `@AcrossApplication` adds the necessary Spring Boot auto configuration classes for embedded servlet containers.
If you have for example *spring-boot-starter-tomcat* on the classpath, you can run an Across based application inside an embedded Tomcat using `SpringApplication`.

.Abbreviated logging output during application startup
----
...
INFO --- [  restartedMain] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http) # <1>
INFO --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat] # <2>
INFO --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.27
INFO --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
...
INFO --- [  restartedMain] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http) # <3>
INFO --- [  restartedMain] com.example.demo.DemoApplication         : Started DemoApplication in 3.36 seconds (JVM running for 7.7) # <4>
----

<1> The embedded tomcat server is being initialized.
By default, it will start the application on port 8080, this can also be configured using the `server.port` property.
<2> The tomcat server is being started.
<3> The tomcat server is fully started.
<4> The application has fully started.