= Temporary changelog for Across 3.0.0

* exposed bean definitions are now copied to the module context directly instead of shared via the parent `ApplicationContext`
* *META-INF/across.configuration* where you can specify Exposed classes, or AutoConfigurationDisabled, AutoConfigurationEnabled
* the latter allows specifying a different class to be executed instead of (using *:*) or a module name where the class should be inserted instead (using *->*)
* the main application class package is not registered as an auto configuration package, instead the package of the application module is
* provided some tests-projects in the across-autoconfigure project. These tests check the integration of several spring-boot-starter artifacts and their autoconfiguration within Across. They also serve as an example on how to setup such a spring-boot-starter with minimal configuration. See <<spring-boot-starters,Spring Boot Starters 1.5.x>>
  
== AcrossWebModule
* `RestTemplateBuilder` is created and exposed
* Jackson `ObjectMapper` and `Jackson2ObjectMapperBuilder` are created and exposed
* if Gson on the classpath: `Gson` object created and exposed

Extension configuration that should be added to AcrossWebModule:

* `RestTemplateCustomizer`
* `HttpMessageConverter`
* `Jackson2ObjectMapperBuilderCustomizer`

.Filter registration
Filters and servlets are registered in a slightly different fashion than in previous versions.
Any `Servlet` or `Filter` bean will now be automatically be exposed and registered.
If there is an actual registration bean for the filter or servlet, it will take precedence.

The new approach might introduce breaking changes with applications that do not use an embedded application context.
The `AcrossWebDynamicServletConfigurer` is fully deprecated and any beans of that type created in the parent context will not be executed any longer in a non-embedded configuration.

Also the ordering of filters might have changed slightly, modules providing filters should review the order assignment.

Dynamically registered filters should preferably include an explicit order value and should be done inside the Across context (inside a module) and not on the application configuration level.

== Unsupported auto-configuration classes
The following is the list of auto-configuration classes that are never automatically enabled.
They are not added to the application configuration and none of the standard modules include them.

In many cases, these can still be added directly using an `@Import` statement inside an application or module.

`org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration`::
Across always packages Liquibase but uses installers instead of a default changeset xml.
Looks like the auto-configuration breaks in this case.

`org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration`:: 
If you want method validation in a module, it should be ok to manually add this auto-configuration.
Adding it on application level will only impact the application infrastructure.
If you want to use a single shared `Validator` bean you should consider exposing it in the module where it first gets created (or also created on application level).

[[spring-boot-starters]]
= Spring Boot starters 1.5.x
Lists the support status of different Spring Boot starters and how you can use them in an Across application.

== Support levels explained

Not supported:: 
  No auto-configuration possible.

Full support::
Virtually no difference compared to a regular Spring Boot application.
Support is automatic in all modules configured in an application.
Common case: web controllers, actuator endpoints...

Application support::
Auto-configuration works as expected for an Across application.
Infrastructure is usually configured on the application level, automatic support is only activated in the application module. Shared modules require manual configuration.
Common case: Spring Data repositories

Partial support::
Auto-configuration is partially supported.
Additional manual configuration is still required.

== Status explained

Expected::
  Currently not yet available.
  
To be verified::
  Auto-configuration available but not yet - or only partially - verified.
  Some cases might not yet work as expected.

Verified::
  Support level is available as indicated.

== Spring Boot Starter Activemq
https://spring.io/guides/gs/messaging-jms/

TBD

== Spring Boot Starter Actuator
https://spring.io/guides/gs/actuator-service/
[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|none
|===

Endpoints, metrics, health indicators from all modules will automatically be exposed and detected.

== Spring Boot Starter amqp
https://projects.spring.io/spring-amqp/

TBD   

== Spring Boot Starter Aop

TBD           

== Spring Boot Starter Artemis

TBD          

== Spring Boot Starter Batch

TBD

== Spring Boot Admin
https://github.com/codecentric/spring-boot-admin

Autoconfiguration classes:

* ``@EnableAdminServer``
* ``AdminServerImportSelector``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|known issues
|===

Known issues:

* date conversion issue on Audit tab

== Spring Boot Admin Starter Client
https://github.com/codecentric/spring-boot-admin

Autoconfiguration classes:

* ``SpringBootAdminClientAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

Known issues:

* date conversion issue on Audit tab

== Spring Boot Starter Cache

TBD
            
== Spring Boot Starter Cloud Connectors

TBD
            
== Spring Boot Starter Data Cassandra
https://projects.spring.io/spring-data-cassandra/

Autoconfiguration classes:

* ``CassandraAutoConfiguration``
* ``CassandraDataAutoConfiguration``
* ``CassandraRepositoriesAutoConfiguration``


[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===
            
== Spring Boot Starter Data Couchbase
https://projects.spring.io/spring-data-couchbase/

Autoconfiguration classes:

* ``CouchbaseAutoConfiguration``
* ``CouchbaseDataAutoConfiguration``
* ``CouchbaseRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|known issues
|===

Known issues:

* CouchbaseMock used for testing doesn't fully support spring data repositories

== Spring Boot Starter Data Elasticsearch
https://projects.spring.io/spring-data-elasticsearch/

Autoconfiguration classes:

* ``ElasticsearchAutoConfiguration``
* ``ElasticsearchDataAutoConfiguration``
* ``ElasticsearchRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===
            
== Spring Boot Starter Data Gemfire

TBD
            
== Spring Boot Starter Data JPA

TBD
            
== Spring Boot Starter Data Ldap
https://projects.spring.io/spring-data-ldap/

Autoconfiguration classes:

* ``LdapAutoConfiguration``
* ``EmbeddedLdapAutoConfiguration``
* ``LdapDataAutoConfiguration``
* ``LdapRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===
            
== Spring Boot Starter Data Mongodb
https://projects.spring.io/spring-data-mongodb/

Autoconfiguration classes:

* ``MongoAutoConfiguration``
* ``EmbeddedMongoAutoConfiguration``
* ``MongoDataAutoConfiguration``
* ``MongoRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===
            
== Spring Boot Starter Data Neo4j
https://projects.spring.io/spring-data-neo4j/

Autoconfiguration classes:

* ``Neo4jDataAutoConfiguration``
* ``Neo4jRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===
            
== Spring Boot Starter Data Redis
https://projects.spring.io/spring-data-redis/

Autoconfiguration classes:

* ``RedisAutoConfiguration``
* ``RedisRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

[[spring-boot-starter-data-rest]]
== Spring Boot Starter Data REST

https://projects.spring.io/spring-data-rest/

Autoconfiguration classes:

* ``RepositoryRestMvcAutoConfiguration``
* ``HibernateJpaAutoConfiguration``, not included by default
* ``JpaRepositoriesAutoConfiguration``, not included by default

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|To be verified
|known issues
|===

Known issues:

* Integration with AcrossHibernateModule and AcrossHibernateJpaModule have not been reviewed yet.
* To use AutoConfiguration of ``HibernateJpaAutoConfiguration`` and ``JpaRepositoriesAutoConfiguration``
you need to add them manually to your across.configuration file.
            
== Spring Boot Starter Data SOLR
https://projects.spring.io/spring-data-solr/

Autoconfiguration classes:

* ``SolrAutoConfiguration``
* ``SolrRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

== Spring Boot Starter Freemarker

TBD
            
== Spring Boot Starter Groovy Templates

TBD
            
== Spring Boot Starter Hateoas

Spring Boot Data Rest includes hateoas, see <<spring-boot-starter-data-rest,Spring Boot Starter Data Rest>>
            
== Spring Boot Starter Integration

TBD
            
== Spring Boot Starter JDBC

TBD
            
== Spring Boot Starter Jersey

TBD
            
== Spring Boot Starter Jetty

Autoconfiguration classes:

* ``JettyEmbeddedServletContainerFactory``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===
            
== Spring Boot Starter Jooq

TBD
            
== Spring Boot Starter JTA Atomikos

TBD
            
== Spring Boot Starter JTA Bitronix

TBD
            
== Spring Boot Starter JTA Narayana

TBD
            
== Spring Boot Starter log4j2

TBD
            
== Spring Boot Starter Logging

Autoconfiguration classes:

* ``LoggingApplicationListener``

LoggingApplicationListener
[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===
            
== Spring Boot Starter Mail

Autoconfiguration classes:

* ``MailSenderAutoConfiguration``
* ``MailSenderValidatorAutoConfiguration``


[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===
            
== Spring Boot Starter Mobile

TBD
            
== Spring Boot Starter Mustache

TBD
            
== Spring Boot Starter Remote Shell

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|Will be deprecated in Spring Boot 2.0.0
|===

WARNING: This Spring Starter will be removed in Spring Boot 2.0.0 so hasn't been reviewed fully.
            
== Spring Boot Starter Security

TBD
            
== Spring Boot Starter Social Facebook

TBD
            
== Spring Boot Starter Social Linkedin

TBD
            
== Spring Boot Starter Social Twitter

TBD
            
== Spring Boot Starter Test

TBD
            
== Spring Boot Starter Thymeleaf

TBD
            
== Spring Boot Starter Tomcat

Autoconfiguration classes:

* ``TomcatEmbeddedServletContainerFactory``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===
            
== Spring Boot Starter Undertow

Autoconfiguration classes:

* ``UndertowEmbeddedServletContainerFactory``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===
            
== Spring Boot Starter Validation

TBD
            
== Spring Boot Starter Web Services

TBD
            
== Spring Boot Starter Web

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|none
|===
            
== Spring Boot Starter Websocket

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|To be verified
|none
|===

