= Temporary changelog for Across 3.0.0

* exposed bean definitions are now copied to the module context directly instead of shared via the parent `ApplicationContext`
* *META-INF/across.configuration* where you can specify Exposed classes, or AutoConfigurationDisabled, AutoConfigurationEnabled
  * the latter allows specifying a different class to be executed instead of (using *:*) or a module name where the class should be inserted instead (using *->*)
  
  
== AcrossWebModule
* `RestTemplateBuilder` is created and exposed
* Jackson `ObjectMapper` and `Jackson2ObjectMapperBuilder` are created and exposed
* if Gson on the classpath: `Gson` object created and exposed

Extension configuration that should be added to AcrossWebModule:

* `RestTemplateCustomizer`
* `HttpMessageConverter`
* `Jackson2ObjectMapperBuilderCustomizer`

== Unsupported auto-configuration classes
The following is the list of auto-configuration classes that are never automatically enabled.
They are not added to the application configuration and none of the standard modules include them.

In many cases, these can still be added directly using an `@Import` statement inside an application or module.

`org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration`::
Across always packages Liquibase but uses installers instead of a default changeset xml.
Looks like the auto-configuration breaks in this case.

`org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration`:: 
If you want method validation in a module, it should be ok to manually add this auto-configuration.
Adding it on application level will only impact the application infrastructure.
If you want to use a single shared `Validator` bean you should consider exposing it in the module where it first gets created (or also created on application level).

= Spring Boot starters
Lists the support status of different Spring Boot starters and how you can use them in an Across application.

== Support levels explained!

Not supported:: 
  No auto-configuration possible.

Full support::
Virtually no difference compared to a regular Spring Boot application.
Support is automatic in all modules configured in an application.
Common case: web controllers, actuator endpoints...

Application support::
Auto-configuration works as expected for an Across application.
Infrastructure is usually configured on the application level, automatic support is only activated in the application module. Shared modules require manual configuration.
Common case: Spring Data repositories

Partial support::
Auto-configuration is partially supported.
Additional manual configuration is still required.

*Status explained*

Expected::
  Currently not yet available.
  
To be verified::
  Auto-configuration available but not yet - or only partially - verified.
  Some cases might not yet work as expected.

Verified::
  Support level is available as indicated.
  
== Actuator
[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|none
|===

Endpoints, metrics, health indicators from all modules will automatically be exposed and detected.

== Spring Boot Admin
[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|known issues
|===

Known issues:

* date conversion issue on Audit tab










