:module-artifact: across-web
:module-name: AcrossWebModule

[#general-information]
= General information

[#about]
== About
AcrossWebModule is the only module included in the Across framework project.
It is the base module added to pretty much any Across web application.

AcrossWebModule activates Spring MVC support for all modules in an AcrossContext.
This means modules can configure the Spring MVC support, add controllers, servlets and filters.

On top of that, the out-of-the-box Spring MVC functionality is extended in several ways:

 * a <<thymeleaf-dialect,Thymeleaf dialect>> is provided for interacting with the Across web infrastructure
 * AcrossWebModule provides infrastructure for <<layout-templates,templates>>, <<menu-infrastructure,menu building>> and <<web-resource-registry,registering web resources>>
 * adding a <<viewelement-infrastructure,programmatic model for creating UI components>> from code
 * adding support for <<request-mapping-extensions,prefixing request mappings and adding custom request condition>>
 * auto configuration of a <<multipart-support,Multipart filter>>
 * auto configuration of static resources with <<client-side-caching,client-side caching>> and <<resource-url-versioning,url versioning>>

AcrossWebModule is not a Web CMS, it only supplies some common infrastructure generally useful when building web applications.
Other modules like link:https://across.dev/modules/WebCmsModule[WebCmsModule] provide CMS features on top of Across Web.

[#artifact]
== Artifact
[source,xml,indent=0]
[subs="verbatim,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across</groupId>
			<artifactId>across-web</artifactId>
		</dependency>
	</dependencies>
----

