[[static-resources]]
[#static-resources]
= Static resources

[abstract]
--
This page explains the support for static resources activated by Across Web.
On this page you will learn:

* [*] the embedded resource conventions for static resource files (css, js) and Thymeleaf templates
* [*] how to configure static resource (client-side) caching
* [*] how to configure static resource url versioning

See the chapter on xref:web-views/web-resources.adoc[web resources] if you are looking for information on the `WebResourceRegistry` and programmatic registration of web resources.
--

Across Web automatically enables serving of static resources bundled with modules.
With the default settings static resources will be configured with <<resource-url-versioning,versioned urls>> and <<client-side-caching,client-side caching>>.

[[static-resources-conventions]]
[#conventions]
== Conventions
The default resources are contains in the `/views` folder on the classpath, and Across Web will serve resources from `/views/static`.
Additional subfolders to serve can be configured with the *acrossWebModule.resources.folders* property.

By convention (and for best development mode support) module specific resources should be located in a subfolder with the `resourcesKey` of the module.

.Example resources layout for MyModule
[source,text,indent=0]
[subs="verbatim,quotes,attributes"]
----
src/main/resources
   views/
     static/
       MyModule/
         js/controller.js
         css/my-module.css
         img/logo.png
     th/
       MyModule/
         controller.html
         user-profile.html
----

The relative path under which the static resources are available is determined by the *acrossWebModule.resources.path* property.

include::static-resources-versioning.adoc[]