[[WebResourceRegistry]]
[#web-resource-registry]
=== WebResourceRegistry
AcrossWebModule allows for programatically registering web resources through the use of a `WebResourceRegistry`.
A new `WebResourceRegistry` is attached to every request and can be accessed as a request attribute or a handler method parameter.

Resources can be added in a bucket.

AcrossWebModule supports 3 bucket types by default: css, javascript, meta.

You can add your own type by, see TODO:LINK.
//TODO: fix link

This bucket can be used for retrieval of resources, for example when rendering inside a thymeleaf template.

Resources can be identified with a unique key, ensuring they are added only once.

==== Javascript bucket type

You can add a javascript type to the `WebResourceRegistry` by using following syntax:

.Example controller registering Javascript resources
[source,java,indent=0]
----
@Controller
public class MyController
{
  @ModelAttribute
  public void registerWebResources( WebResourceRegistry webResourceRegistry ) {
    webResourceRegistry.add( WebResource.javascript().url("//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js").defer().async() ); # <1>
    webResourceRegistry.add( WebResource.javascript().url("@static:/adminweb/js/file.js") ); # <2>
    webResourceRegistry.add( WebResource.javascript().inline( "alert('hello world');") ); # <3>
    webResourceRegistry.add( WebResource.javascript().data( Collections.singletonMap( "PI", "3.14159265359"  ) ) ); # <4>
  }
}
----

<1> This adds an external Javascript file to the javascript bucket, it will put the attributes `defer` and `async` on it
<2> This adds a Javascript file located under the default static folder
<3> This inlines Javascript directly into a script tag
<4> This inline a data object into the script tag

You can render the *javascript* bucket, with the following snippet:

.Example rendering in thymeleaf
[source,html,indent=0]
----
<html>
<head>
    <across:view element="${javascript}" th:each="javascript :${webResourceRegistry.getResourceBucket('javascript')}" />
</head>
<body>
...
</body>
</html>
----

//TODO: revise data object
.Generated output by thymelaf for the above example
[source,html,indent=0]
----
<html>
<head>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" type="text/javascript" defer async></script>
    <script src="/static/adminweb/js/file.js" type="text/javascript"></script>
    <script type="text/javascript">alert('hello world()');</script>
    <script type="text/javascript">
        (function( Across ) {
            Across[ "PI" ] = "3.14159265359";
        })( window.Across = window.Across || {} );
    </script>
</head>
<body>
...
</body>
</html>
----

==== CSS bucket type

You can add a css type to the `WebResourceRegistry` by using following syntax:

.Example controller registering CSS resources
[source,java,indent=0]
----
@Controller
public class MyController
{
  @ModelAttribute
  public void registerWebResources( WebResourceRegistry webResourceRegistry ) {
    webResourceRegistry.add( WebResource.css().url("//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css") ); # <1>
    webResourceRegistry.add( WebResource.css().url("@static:/adminweb/css/print.css").rel("stylesheet").media("print") ); # <2>
    webResourceRegistry.add( WebResource.css().inline("body {background-color: powderblue;}") ); # <3>
  }
}
----

<1> This adds an external CSS file to the css bucket.
<2> This adds a CSS file located under the default static folder, it will put the attributes `media` and `rel` on it
<3> This inlines CSS directly into a style tag

You can render the *css* bucket, with the following snippet:

.Example rendering in thymeleaf
[source,html,indent=0]
----
<html>
<head>
    <across:view element="${css}" th:each="css :${webResourceRegistry.getResourceBucket('css')}" />
</head>
<body>
...
</body>
</html>
----

.Generated output by thymelaf for the above example
[source,html,indent=0]
----
<html>
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" type="text/css"></script>
    <link href="/static/adminweb/css/print.css" type="text/css" rel="stylesheet" media="print"></script>
    <style>
        body {background-color: powderblue;}
    </style>
</head>
<body>
...
</body>
</html>
----

==== Meta bucket type

You can add a meta type to the `WebResourceRegistry` by using following syntax:

.Example controller registering META resources
[source,java,indent=0]
----
@Controller
public class MyController
{
  @ModelAttribute
  public void registerWebResources( WebResourceRegistry webResourceRegistry ) {
    webResourceRegistry.add( WebResource.meta().name("keywords").content("HTML, CSS, XML, HTML") ); # <1>
    webResourceRegistry.add( WebResource.meta().refresh("30;URL='https://www.google.com/'") ); # <2>
  }
}
----

<1> This will generate a META tag and will put the attributes `name` and `content` on it.
<2> This generate a `http-equiv` META tag with a refresh timer of 30 seconds, towards https://www.google.com.

You can render the *meta* bucket, with the following snippet:

.Example rendering in thymeleaf
[source,html,indent=0]
----
<html>
<head>
    <across:view element="${meta}" th:each="meta :${webResourceRegistry.getResourceBucket('meta')}" />
</head>
<body>
...
</body>
</html>
----

.Generated output by thymelaf for the above example
[source,html,indent=0]
----
<html>
<head>
    <meta name="keywords" content=""HTML, CSS, XML, HTML"" />
    <meta http-equiv="refresh" content="30;URL='https://www.google.com/'" />
</head>
<body>
...
</body>
</html>
----
==== Custom bucket type

It is possible to register your own bucket type by using following syntax:

.Example controller registering `base` resources
[source,java,indent=0]
----
@Controller
public class MyController
{
 @ModelAttribute
 public void registerWebResources( WebResourceRegistry webResourceRegistry ) {
   webResourceRegistry.add( WebResource.create("base").attr( Collections.singletonMap( "href", "https://www.w3schools.com/images/"  ) ) ); # <1>
 }
}
----

<1> Generates a `base` tag with the `href` attribute.

You can render the custom bucket, with the following snippet:

.Example rendering in thymeleaf
[source,html,indent=0]
----
<html>
<head>
    <across:view element="${base}" th:each="base :${webResourceRegistry.getResourceBucket('base')}" />
</head>
<body>
...
</body>
</html>
----

.Generated output by thymelaf for the above example
[source,html,indent=0]
----
<html>
<head>
    <base href="https://www.w3schools.com/images/"  />
</head>
<body>
...
</body>
</html>
