== Advanced topics

[[bootstrap-events]]
[#dev-appl-bootstrap-events]
=== Lifecycle events
When starting an Across context, a number of events are published.
These allow you to hook into the Across context lifecycle.

AcrossModuleBeforeBootstrapEvent::
Event that is sent for each module, right before it is bootstrapped.
The configuration of the module can still be modified at this point.
Modules will only receive this event for other modules that are started later during the bootstrap phase.

AcrossModuleBootstrappedEvent::
Event published when a module has bootstrapped.
That means the module itself has started, but installers attached to the `AfterModuleBootstrap` phase have not yet been executed.
Modules will only receive this event for other modules that are started later during the bootstrap phase.

AcrossContextBootstrappedEvent::
Event published after the AcrossContext has bootstrapped.
That means full initialization has happened: all modules are started and all installers have been executed.

WARNING: Because of component creation order, lifecycle events can often not be handled using regular `@EventListener` methods.
You should provide an `ApplicationListener` component for those events instead. A general purpose interface `AcrossLifecycleListener` can be implemented if you want to handle more than one lifecycle event.

=== Customizing Across bootstrap
If is possible to customize an Across context configuration after the modules have been assembled, but before the actual context or module starts.
There are two common ways to do this:

. handling the `AcrossModuleBeforeBootstrapEvent` and customizing the configuration of the module being started
. providing one or more `AcrossBootstrapConfigurer` components in the parent `ApplicationContext`
** for example: have your `@AcrossApplication` annotated class implement the `AcrossBootstrapConfigurer` interface
** this strategy is often used for providing auto-configuration support of third-party libraries

Additionally, a shared module can also modify the Across context configuration by implementing `prepareForBootstrap()` on its module descriptor.


