[[across-datasource]]
[#across-datasource]
= Connecting to a database

////
* h2-console
////

== The Across DataSource
An Across context supports the configuration of a `DataSource` instance.
If there is a primary `DataSource` or only a single `DataSource` bean available, Across will automatically use that one.

The datasource will be available for all modules as a bean named *acrossDataSource*.
Additionally a second datasource can be configured that will be available as the *acrossInstallerDataSource*.
If no separate installer datasource is specified, the default across datasource will be used.

.Installers
Across only actually needs a datasource if you want to execute installers or use the `DistributedLockRepository` directly.
The datasource is used for keeping track of which installers have been executed.

See for more information on working with SQL databases in an Across application, see the <<sql-databases,separate chapter>>.

[[sql-databases]]
== Working with SQL databases
An Across application supports virtually all features of a regular Spring Boot application when it comes to working with SQL databases.
You can automatically create a `DataSource` instance by setting the right properties and adding a starter like `spring-boot-starter-jdbc` or `spring-boot-starter-jpa`.

.Example configuring a datasource bean
[source,properties]
----
spring.datasource.url=jdbc:mysql://localhost/test
spring.datasource.username=dbuser
spring.datasource.password=dbpass
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
----

See the link:{spring-boot-docs}#boot-features-sql[relevant Spring Boot documentation] for an overview of the possible features.
The rest of this chapter lists the most important differences between a regular Spring Boot and an Across application.

// multiple databases -> see the guide

////
=== Using JdbcTemplate
Currently not supported.

=== JPA and Spring Data
When adding `spring-boot-starter-data-jpa` a JPA `EntityManager` using Hibernate 5 will be automatically created and available in the application module.
The *application module package will be scanned for entities and Spring Data JPA repositories*, in the same way as described in the link:{spring-boot-docs}#boot-features-jpa-and-spring-data[Spring Boot documentation].

Default support is limited to the application module however.
If you are looking for JPA support for multiple (shared) modules, you should look at the link:{across-hibernate-module-url}[AcrossHibernateJpaModule].
Said module creates a shared `EntityManager` with a mapping context that other modules can extend.
It is also fully compatible with the default Spring Boot JPA support and can often be used as a simple drop-in replacement when switching from a simple application to having multiple modules with entities.

WARNING: When only using the `spring-boot-starter-data-jpa` the database schema will be created by default when using an embedded database.
When switching to AcrossHibernateJpaModule as a replacement, you will always have to specify the schema creation.

////