[[development-mode]]
[#development-mode]
= Development mode
// what is development mode?
Development mode offers a variety of tools to boost a developers productivity during development.
It can be used by modules to configure different services (or services differently).
For example auto-reloading and no caching of the message sources if development mode is active.

Development mode is activated if one of the following conditions applies:

* The `developmentMode` property on the `AcrossContext` has been set
* The property `across.development.active` is _true_
* The `dev` xref:application-configuration.adoc#application-profiles[application profile] is active

== Resource resolving
By default resources (eg. messages, templates) are resolved from the classpath.
Development mode allows the configuration of a physical location for the resources of a module (eg on your local filesystem).

_Default location_ +
For simple Across based applications using `@AcrossApplication` it might be enough to simply activate development mode.
If the working directory of the running application contains a `src/main/resources` directory, this directory would be used for all dynamic modules, unless a specific value is set.
This would usually be the case for single maven module projects.

_Specific module resource locations_ +
The path can be configured by adding the right property to the xref:application-configuration.adoc#configuration-properties[application properties], or specifying them in the development mode properties.
The development mode properties is a special properties file that by default will be looked for in `${user.home}/dev-configs/across-devel.properties`.

A resource location for the development mode properties can be specified by setting the `across.development.properties` property value.
Development mode properties are loaded using resource resolving, so classpath resources can be used as well (eg. `classpath:/dev.properties`).

The development mode properties file should contain properties where the key references the module name, and the value the physical resources directory.

.Example development properties
[source,text,indent=0]
[subs="verbatim,quotes,attributes"]
----
# Absolute directory
acrossModule.MyModule.resources=c:/code/mymodule/src/main/resources
acrossModule.OtherModule.resources=c:/code/othermodule/src/main/resources

# Relative to the working directory
acrossModule.SomeModule.resources=some-module/src/main/resources
----

NOTE: Using relative paths can be an effective way to embed development properties in a multi-module maven project.
Paths should be relative to the working directory of the running application.
Depending on how you run the application, the working directory can differ.

WARNING: Properties added directly to the application properties will take precedence over those present in the development mode properties.

// devtools!
== Developer tools
Development mode also activates support for link:https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html[Spring Boot DevTools].
These tools provide the developer with various productivity features, such as hot-relod, where simply a recompile is required instead of restarting the entire application.

// can also be activated using AcrossContextConfigurer
== Customizing the AcrossContext
After initial configuration and before any modules have been bootstrapped before bootstrapping, the configured `AcrossContext` will be delegated to all `AcrossContextConfigurer` beans it can find in the `ApplicationContext`.
This allows the `AcrossContext` to be modified before the actual bootstrap happens.

.Example customizing an AcrossContext
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
|===
@Configuration
@EnableAcrossContext
public class WebConfiguration implements AcrossContextConfigurer # <1>
{
	@Bean
	public DataSource acrossDataSource() { # <2>
		BasicDataSource dataSource = new BasicDataSource();
		dataSource.setDriverClassName( "org.hsqldb.jdbc.JDBCDriver" );
		dataSource.setUrl( "jdbc:hsqldb:mem:/hsql/testDataSource" );
		dataSource.setUsername( "sa" );
		dataSource.setPassword( "" );

		return dataSource;
	}

	@Override
	public void configure( AcrossContext context ) { # <3>
		context.setDevelopmentMode( true );

		context.addModule( new SomeModule() );
	}
}
|===
<1> All AcrossContextConfigurers that are found in the ApplicationContext are called with the initial AcrossContext.
<2> A xref:connecting-to-a-database.adoc[datasource bean] is creaed.
<3> The `AcrossContext` is being injected and modified.