[#3-0-0-SNAPSHOT]
=== 3.0.0-SNAPSHOT
Across 3.0.0 is a big internal upgrade focused on improving Spring Boot compatibility.
Although the number should be limited, this release does introduce some breaking changes.

Across Framework 3.0.0 adds the `across-autoconfigure` artifact as a base dependency for creating Across applications.
It is also the first release with auto-configuration support, see the separate documentation on link:{doc-spring-boot}#spring-boot[Spring Boot compatibility] for more details.

*Core dependency upgrades*

* Spring Platform Brussels-SR6
* Spring Framework 4.3.13
* Spring Boot 1.5.9

*Across Core*

* addition of the `@ConditionalOnAcrossModule` annotation that can be put on a `@Configuration` class, `@Bean` method and any `@Component` to depend on the presence of modules.
** `@AcrossDepends` should now only be used on module descriptors, and no longer for conditional component creation
* exposed bean definitions are now copied to the module context directly instead of shared via the parent `ApplicationContext`
** this improves compatibility with a lot of default Spring related configurations, but might introduce a breaking change for certain modules
* the event handling system has been overhauled and now uses the default Spring events implementation
** the custom event bus using MBassador has been removed, as well as the MBassador dependency itself
** implementing `AcrossEvent` for your own events is no longer required
** `@Event` has been deprecated in favour of the standard `@EventListener`
** `AcrossEventPublisher` has been deprecated in favour of the standard `ApplicationEventPublisher`
** `ParameterizedAcrossEvent` has been deprecated in favour of implementing `ResolvableTypeProvider`
** `@EventName` has been deprecated, use the `condition` attribute on `@EventListener` instead
** Please note that generic event types are handled differently with the new system, where in the past
`SomeEvent<Object>` would have worked, the only working (and more correct) signature is now `SomeEvent<? extends Object>`
** parameter-less event listener methods are now possible
** event listener methods can now also provide return values which will be published as new events
** ordering event listeners through annotations on a method level is now supported
** events `AcrossModuleBeforeBootstrapEvent`, `AcrossModuleBootstrappedEvent` and `AcrossContextBootstrappedEvent` now extend `AcrossLifecycleEvent` which implements the Spring `ApplicationEvent` directly
*** a utility interface `AcrossLifecycleListener` has been provided to intercept these common lifecycle events
** some breaking changes that have been introduced as a result of the refactoring:
*** any uncaught exception in an event listener will now bubble up to the caller and stop the subsequent listeners from being called, instead of just logging the exception and continuing to the next listener
*** manual (de-)registration of event listeners on `AcrossEventPublisher` is no longer possible
*** bootstrap events can no longer be captured through annotated methods in the parent `ApplicationContext`, implement `AcrossLifecycleListener` instead
* add support for Spring Boot auto-configuration and the `META-INF/across.configuration` file inside libraries
* addition of `AcrossBootstrapConfigurer` that can be used to customize a bootstrapping Across context from a parent `ApplicationContext` (for example for auto-configuration classes)
* bean definition names generated for `@Configuration` or manually registered annotated classes (without `@Component`) are now always based on the fully qualified class name
** in rare cases this could introduce a breaking change where configuration instances are wired by name as beans, in this case providing an explicit name for the configuration should fix the problem
* it's now possible to explicitly exclude annotated classes to be loaded as module extension during bootstrap configuration
* the default module scanning packages will now always be kept if you add additional packages on either `@EnableAcrossContext` or `@AcrossApplication`
** if you explicitly want to exclude the default packages you should add *.* (dot) as a package name to the list
* Bean Validation 1.1 method validation is now automatically enabled in every Across module if a JSR-303 implementation (eg. Hibernate validator) is on the classpath
* the `TransactionManagementConfigurer` helper class has been removed from the core artifact
** modules should provide their own implementation when necessary
* `ComponentScanConfigurer.forAcrossModule(Class)` and `ComponentScanConfigurer.forAcrossModulePackage(String)` helper functions have been added to create default configurations for modules wishing to scan their entire root package
** these will correctly exclude the `installers` and `extensions` child package
** default `AcrossModule` implementations still only scan the `config` child package

*AcrosWebModule*

A lot of internal configuration has been modified to use out-of-the-box Spring Boot configuration classes instead of customized versions.

The following changes and additions are included in the update:

* a `RestTemplateBuilder` is created and exposed
* Jackson `ObjectMapper` and `Jackson2ObjectMapperBuilder` are created and exposed
* if Gson on the classpath: a `Gson` object created and exposed
* support for link:{doc-across-web}#error-handling[default error pages] is now automatically activated
* the https://github.com/thymeleaf/thymeleaf-extras-java8time[Thymeleaf Java 8 Time dialect] is now also included and enabled
* the default mvc `Validator` bean now implements `SmartValidator` directly, allowing `@Validated` with group validation to be used
* the `TextViewElementBuilder` now supports a link:{doc-across-web}#localized-text[localized text pattern] as text value
* several changes to the menu building infrastructure, some breaking. See the link:{doc-across-web}#menu-building[updated documentation] for use case examples.
** added `Menu.builder()` for easy ad-hoc creation of a menu using path registration
** `MenuSelector` factory methods have been moved from the `Menu` to `MenuSelector` class
** some rarely used methods on `PathBasedMenuBuilder`, `PathBasedMenuItemBuilder` and `BuildMenuEvent` have been removed
** `BuildMenuFinishedEvent` has been removed, modules requiring this functionality should now register a `Menu` post-processor on the `BuildMenuEvent` instead
** renamed methods on `BuildMenuEvent`:
*** `setSelector()` -> `setMenuSelector()`, `getSelector()` -> `getMenuSelector()`
*** `forMenu()` -> `isForMenuOfType()`
** options to customize a menu have been improved and some new ones have been added:
*** on a menu builder these are `changeItemPath()`, `removeItems()`, `optionalItem()` and `withProcessor()`
*** on a menu item builder these are `changePathTo()`, `remove()` and `comparator()`
*** the unreliable `move()` method for menu items has been deprecated, use the new `changeItemPath()` or `item().changePathTo()` instead
*** using `PathBasedMenuBuilder.andThen()` it is now possible to register and apply additional configuration after all initial configuration has been done.
This is especially useful if you want to make changes to a menu builder when you want to be sure all intial items have been added.

.New module extension support
Extension configuration classes that can now be added to AcrossWebModule:

* `RestTemplateCustomizer`
* `HttpMessageConverter`
* `Jackson2ObjectMapperBuilderCustomizer`

.Changes in servlet and filter registration
Filters and servlets are registered in a slightly different fashion than in previous versions.
Any `Servlet` or `Filter` bean will now be automatically be exposed and registered.
If there is an actual registration bean for the filter or servlet, it will take precedence.

The new approach might introduce breaking changes with applications that do not use an embedded application context.
The `AcrossWebDynamicServletConfigurer` is fully deprecated and any beans of that type created in the parent context will not be executed any longer in a non-embedded configuration.

Also the ordering of filters might have changed slightly, modules providing filters should review the order assignment.

Dynamically registered filters should preferably include an explicit order value and should be done inside the Across context (inside a module) and not on the application configuration level.
