== Framework artifacts
Across framework itself consists of 4 library artifacts (`across-core`, `across-web`, `across-autoconfigure` and `across-test`) and one bill-of-material pom (`standard-module-bom`).

across-core:: Supports the configuration of an Across context and provides all necessary infrastructure to define and execute modules.
across-web:: Provides an `AcrossModule` that supports configuration of a web application using Across with the Spring `DispatcherServlet` as the most common scenario.
across-autoconfigure:: Simplifies configuration of a Spring Boot based Across application.
This is usually the base dependency for an application, as it transitively imports both core and web.
across-test:: Supports integration testing of your Across modules, both web and non-web related.  Builds on top of `spring-test`.
standard-module-bom:: BOM pom for creating an Across Standard Module or any module wishing to adhere to the standard module conventions.

There is also a separate {platform-bom-url}[platform-bom] project that provides a bill-of-material for applications built on Across and the Across Standard Modules.

.Common dependencies
Across is directly tied to Spring framework and all artifacts come with a set of curated dependencies.
Across itself uses the http://platform.spring.io/platform/[Spring IO platform] as a basis for all its dependencies.

.Artifact repositories
All release versions of Across artifacts are available on Maven Central.

Snapshot and milestones can be fetched from the Foreach Nexus repository.
This also includes the set of link:{doc-fundamentals}#fundamentals-ax-standard-modules[across standard modules].

[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
<repositories>
    <repository>
        <id>foreach-nexus</id>
        <name>Foreach nexus</name>
        <url>https://repository.foreach.be/nexus/repository/public/</url>
    </repository>
</repositories>
----

