:numbered:
== Not supported
The following is a list of common auto-configuration classes that are never automatically enabled.
They are not added to the application configuration and none of the standard modules include them.

In many cases, these can still be added directly using an `@Import` statement inside an application or module.

`org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration`::
Across always packages Liquibase but uses installers instead of a default changeset xml.
Looks like the auto-configuration breaks in this case.

`org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration`::
If you want method validation in a module, it should be ok to manually add this auto-configuration.
Adding it on application level will only impact the application infrastructure, not any of the modules (this includes the application module).
If you want to use a single shared `Validator` bean you should consider exposing it in the module where it first gets created (or also create it on application level).

`org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration`::
AcrossWebModule provides its own Thymeleaf configuration that differs slightly from the Spring Boot default.
Templates are expected to be in `classpath:/views/*` with `html` extension.
