== Auto-configuration support

=== Support levels explained

Not supported::
  No auto-configuration possible.

Full support::
Virtually no difference compared to a regular Spring Boot application.
Support is automatic in all modules configured in an application.
Common case: web controllers, actuator endpoints...

Application support::
Auto-configuration works as expected for an Across application.
Infrastructure is usually configured on the application level, automatic support is only activated in the application module. Shared modules require manual configuration.
Common case: Spring Data repositories

Partial support::
Auto-configuration is partially supported.
Additional manual configuration is still required.

=== Status explained

Expected::
  Currently not yet available.

To be verified::
  Auto-configuration available but not yet - or only partially - verified.
  Some cases might not yet work as expected.

Verified::
  Support level is available as indicated.


=== Adding auto-configuration support
tbd

==== across.configuration

* *META-INF/across.configuration* where you can specify Exposed classes, or AutoConfigurationDisabled, AutoConfigurationEnabled
* the latter allows specifying a different class to be executed instead of (using *:*) or a module name where the class should be inserted instead (using *->*)
* the main application class package is not registered as an auto configuration package, instead the package of the application module is
* provided some tests-projects in the across-autoconfigure project. These tests check the integration of several spring-boot-starter artifacts and their autoconfiguration within Across. They also serve as an example on how to setup such a spring-boot-starter with minimal configuration. See <<spring-boot-starters,Spring Boot Starters 1.5.x>>

* DynamicApplicationModule & AcrossContextPostProcessorModule

== Unsupported auto-configuration classes
The following is the list of auto-configuration classes that are never automatically enabled.
They are not added to the application configuration and none of the standard modules include them.

In many cases, these can still be added directly using an `@Import` statement inside an application or module.

`org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration`::
Across always packages Liquibase but uses installers instead of a default changeset xml.
Looks like the auto-configuration breaks in this case.

`org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration`::
If you want method validation in a module, it should be ok to manually add this auto-configuration.
Adding it on application level will only impact the application infrastructure.
If you want to use a single shared `Validator` bean you should consider exposing it in the module where it first gets created (or also created on application level).

`org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration`::
AcrossWebModule provides its own Thymeleaf configuration that differs slightly from the Spring Boot default.
Templates are expected to be in `classpath:/views/*` with `html` extension.

[[spring-boot-starters]]
== Starters and libraries
Lists the support status of different Spring Boot starters and how you can use them in an Across application.

:!numbered:
===  Official Spring Boot starters
{spring-boot-docs}#using-boot-starter

==== ActiveMQ
https://spring.io/guides/gs/messaging-jms/

Under investigation.

==== Actuator
https://spring.io/guides/gs/actuator-service/
[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|none
|===

Endpoints, metrics, health indicators from all modules will automatically be exposed and detected.

==== AMQP
https://projects.spring.io/spring-amqp/

Under investigation.

==== AOP

Under investigation.

==== Artemis

Currently not supported, to be investigated.

==== Batch

Under investigation.
There is currently an Across standard module https://across.foreach.be/modules/SpringBatchModule that will most likely be discontinued in favour of auto-configuration.

==== Cache

Under investigation.

==== Cloud Connectors

Under investigation.

==== Data Cassandra
https://projects.spring.io/spring-data-cassandra/

Autoconfiguration classes:

* ``CassandraAutoConfiguration``
* ``CassandraDataAutoConfiguration``
* ``CassandraRepositoriesAutoConfiguration``


[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Data Couchbase
https://projects.spring.io/spring-data-couchbase/

Autoconfiguration classes:

* ``CouchbaseAutoConfiguration``
* ``CouchbaseDataAutoConfiguration``
* ``CouchbaseRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|known issues
|===

Known issues:

* CouchbaseMock used for testing doesn't fully support spring data repositories

==== Data Elasticsearch
https://projects.spring.io/spring-data-elasticsearch/

Autoconfiguration classes:

* ``ElasticsearchAutoConfiguration``
* ``ElasticsearchDataAutoConfiguration``
* ``ElasticsearchRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Data Gemfire

Currently not supported, to be investigated.

==== Data JPA

Under investigation.

==== Data LDAP
https://projects.spring.io/spring-data-ldap/

Autoconfiguration classes:

* ``LdapAutoConfiguration``
* ``EmbeddedLdapAutoConfiguration``
* ``LdapDataAutoConfiguration``
* ``LdapRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Data MongoDB
https://projects.spring.io/spring-data-mongodb/

Autoconfiguration classes:

* ``MongoAutoConfiguration``
* ``EmbeddedMongoAutoConfiguration``
* ``MongoDataAutoConfiguration``
* ``MongoRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Data Neo4j
https://projects.spring.io/spring-data-neo4j/

Autoconfiguration classes:

* ``Neo4jDataAutoConfiguration``
* ``Neo4jRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Data Redis
https://projects.spring.io/spring-data-redis/

Autoconfiguration classes:

* ``RedisAutoConfiguration``
* ``RedisRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

[[spring-boot-starter-data-rest]]
==== Data REST

https://projects.spring.io/spring-data-rest/

Autoconfiguration classes:

* ``RepositoryRestMvcAutoConfiguration``
* ``HibernateJpaAutoConfiguration``, not included by default
* ``JpaRepositoriesAutoConfiguration``, not included by default

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|To be verified
|known issues
|===

Known issues:

* Integration with AcrossHibernateModule and AcrossHibernateJpaModule have not been reviewed yet.
* To use AutoConfiguration of ``HibernateJpaAutoConfiguration`` and ``JpaRepositoriesAutoConfiguration``
you need to add them manually to your across.configuration file.

==== Data SOLR
https://projects.spring.io/spring-data-solr/

Autoconfiguration classes:

* ``SolrAutoConfiguration``
* ``SolrRepositoriesAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Freemarker

Currently not supported, to be investigated.

==== Groovy Templates

Currently not supported, to be investigated.

==== HATEOAS

Spring Boot Data Rest includes hateoas, see <<spring-boot-starter-data-rest,Spring Boot Starter Data Rest>>.

==== Integration

Currently not supported, to be investigated.

==== JDBC

Under investigation.

==== Jersey

Currently not supported, to be investigated.

==== Jetty

Autoconfiguration classes:

* ``JettyEmbeddedServletContainerFactory``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

==== JOOQ

Currently not supported, to be investigated.

==== JTA Atomikos

Currently not supported, to be investigated.

==== JTA Bitronix

Currently not supported, to be investigated.

==== JTA Narayana

Currently not supported, to be investigated.

==== Log4J2

Currently not supported, to be investigated.

==== Logging

Autoconfiguration classes:

* ``LoggingApplicationListener``

LoggingApplicationListener
[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

==== Mail

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

.Autoconfiguration classes
* ``MailSenderAutoConfiguration``
* ``MailSenderValidatorAutoConfiguration``

==== Mobile

Currently not supported, to be investigated.
There is a https://across.foreach.be/modules/SpringMobileModule that integrates with AcrossWebModule to enable Spring mobile support.

==== Mustache

Currently not supported, to be investigated.

==== Remote Shell

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|Will be deprecated in Spring Boot 2.0.0
|===

WARNING: This Spring Starter will be removed in Spring Boot 2.0.0 so hasn't been reviewed fully.

==== Security

Under investigation.

==== Social Facebook

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Social Linkedin

Under investigation.

==== Social Twitter

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Application support
|Verified
|none
|===

==== Test

Fully supported.

==== Thymeleaf

Not supported.
AcrossWebModule configures its own Thymeleaf configuration for template support in modules.

==== Tomcat

Autoconfiguration classes:

* ``TomcatEmbeddedServletContainerFactory``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

==== Undertow

Autoconfiguration classes:

* ``UndertowEmbeddedServletContainerFactory``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

==== Validation

Under investigation.

==== Web Services

Currently not supported, to be investigated.

==== Web

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|none
|===

==== Websocket

Autoconfiguration classes:

* ``WebSocketAutoConfiguration``

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|Requires the @EnableWebSocketMessageBroker provided by Across (com.foreach.across.autoconfigure.websocket.EnableWebSocketMessageBroker)

MessageBrokerRegistry in AbstractWebSocketMessageBrokerConfigurer will overwrite its settings when declared in multiple modules.

Full support to use basic WebSocket requests using WebSocketHandlers.
Requires the @EnableWebSocket annotation provided by Across (com.foreach.across.autoconfigure.websocket.EnableWebSocket)
|===

=== Contributed Spring Boot starters


==== Spring Boot Admin
https://github.com/codecentric/spring-boot-admin

Add `@EnableAdminServer` on your application class to create a Spring Boot admin in your application.

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|To be verified
|none
|===

==== Spring Boot Admin Client
https://github.com/codecentric/spring-boot-admin


[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

.Autoconfiguration classes
* `SpringBootAdminClientAutoConfiguration`

=== Other libraries

==== Swagger2

Use `@EnableSwagger2` on the Across application class to activate Swagger2 support on all controllers in any module.

[cols="1,1,4",opts=header]
|===
|Support level
|Status
|Remarks

|Full support
|Verified
|none
|===

.Autoconfiguration classes
* ``Swagger2AutoConfiguration`` - added by Across autoconfigure project
