= +++ <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 82.9 95.7" width="40" style="margin-right: 10px"><path fill="#3CA873" d="M0 23.9l15.9-9.2 41.5 23.9-16 9.2"></path><path fill="#0093D8" d="M25.5 9.2L41.4 0l41.5 23.9-16 9.2"></path><path fill="#53DD99" d="M41.4 95.7l16-9.3V38.6l-16 9.2"></path><path fill="#22CEFA" d="M66.9 80.9l16-9.2V23.9l-16 9.2"></path><path fill="#257A50" d="M12.5 64.5L28.9 55l-16.4-9.4"></path><path fill="#4DBC86" d="M12.5 64.5L28.9 74V55"></path></svg> +++ Across framework
include::variables.adoc[]

include::../ax-docs-shared/copyright.adoc[]

---

The reference documentation is split up into several parts:

* <<whats-new.adoc#whats-new,What's new in this version>> lists the release notes of the Across framework
* <<fundamentals.adoc#fundamentals,Fundamentals>> explains the fundamental concepts of Across, things you should really understand when building Across applications or modules
* <<developing-applications.adoc#developing-across-applications,Developing Across applications>> goes into some more detail about the steps involved in developing application with Across modules, as well as some of the features you can use
* <<developing-modules.adoc#developing-across-modules,Developing Across modules>> is more geared towards developers interested in creating shared modules - although the information is generally useful
* link:across-web-module/index.adoc[AcrossWebModule] gives an overview of the web specific additions that Across core brings
* <<testing.adoc#across-test,Testing>> explains how developers can integration test their modules or applications

Through the {across-url}[Across website] you can find a lot more information like frequently asked questions, tutorials and available modules (with their respective documentation).
